### ISSUE TITLE
Add ownership to VestingWallet

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/vw-cli#31]
Parent epic: [DF Main E2E](https://github.com/oceanprotocol/df-private/issues/65). [Related GSlides](https://docs.google.com/presentation/d/1obKXDzxpRsQPzRo1gLdpWtKvQdA4UGCYhjezG0X4C-0/edit#slide=id.g21b739be24a_0_2).

### TODOs

- [ ] Add ownership to VestingWallet
- [ ] Contract should be able to removeOwner
- [ ] Add a kill switch; destroy the contract and transfer funds back to owner.

Maybe:
- Make beneficiary address modifiable by the owner.
