### ISSUE TITLE
Implement & test exponential vesting

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/vw-cli#8]
**Motivation**

We need a wallet with exponential vesting, Bitcoin-style (but smooth is ok). Must support 4 year half life.

This is partly implemented, from some work in #5, in commit https://github.com/oceanprotocol/vw-cli/commit/95ca5a9bf12c467b4201936f16ff0169b28104fa.

**TODO**

Pre-requisite: do #7 - test linear vesting better. Because any issues there would otherwise propagate here.

- [ ] New branch
- [ ] Copy VestingWalletLinear.sol into VestingWalletExp.sol. Same for tests and CLI
- [ ] Q: how specifically to have exp'ls in Solidity? Need to investigate
- [ ] Update behavior of .sol to be exponential. Update tests. Test thoroughly
- [ ] Merge
